version: 2.1

orbs:
  node: circleci/node@4.7
  browser-tools: circleci/browser-tools@1.1.0

jobs:
  test:
    docker:
      - image: cimg/node:23.1
    steps:
      - checkout
      - run:
          name: Start API Server
          command: cd ./api_tests && npm install && npm run dev
      - run:
          name: Run API Tests
          command: cd ./api_tests && npm install && npm test
      - store_test_results:
          path: ./api_tests/reports/junit
      - run:
          name: Run tests
          command: cd ui_tests && npm install && npm run test
      - store_test_results:
          path: ./ui_tests/tests_output
            
workflows:
  e2e-test:
    jobs:
      - test