version: 2.1
orbs:
  node: circleci/node@4.7.0

jobs:
  ui_tests:
    executor: node/default
    steps:
      - checkout

      - run:
          name: Navigate to UI tests directory
          command: cd ui_tests

      - node/install-packages:
          pkg-manager: npm

      - run:
          name: Run Nightwatch UI tests
          command: npx nightwatch

  api_tests:
    executor: node/default 
    steps:
      - checkout
      - run:
          name: Navigate to API tests directory
          command: cd api_tests

      - node/install-packages:
          pkg-manager: npm

      - run:
          name: Run Supertest API tests
          command: npx nightwatch

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - ui_tests 
      - api_tests:
          requires:
            - ui_tests
