version: 2.1
executors:
  node-executor:
    docker:
      - image: node:23

jobs:
  ui_tests:
    executor: node-executor
    steps:
      - checkout

      - run:
          name: Install UI test dependencies
          command: |
            cd ui_tests 
            npm install nightwatch chromedriver --save-dev

      - run:
          name: Run Nightwatch UI tests
          command: |
            cd ui_tests 
            npx nightwatch


  api_tests:
    executor: node-executor 
    steps:
       - checkout 

       - run:
          name: Install API test dependencies
          command: |
            cd api_tests
            npm install

       - run:
          name: Run Supertest API tests
          command: |
            cd api_tests
            npm test

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - ui_tests 
      - api_tests:
          requires:
            - ui_tests
