version: 2.1

orbs:
  node: circleci/node@4.7
  browser-tools: circleci/browser-tools@1.1.0

jobs:
  test:
    docker:
      - image: cimg/node:lts-browsers
    steps:
      - checkout
      - browser-tools/install-browser-tools
      - node/install-packages
      - run:
          name: Run UI Tests
          command: cd ui_tests && npm run test
      - run:
          name: Start API Server
          command: cd api_tests && nohup npm run dev &
      - run:
          name: Run API Tests
          command: cd api_tests && npm test
      - store_test_results:
          path: ./ui_tests/tests_output
      - store_test_results:
          path: ./api_tests/reports/junit
            

workflows:
  e2e-test:
    jobs:
      - test