version: 2.1

orbs:
  node: circleci/node@4.7
  browser-tools: circleci/browser-tools@1.1.0

jobs:
  test:
    docker:
      - image: cimg/node:lts-browsers
    steps:
      - checkout
      - browser-tools/install-browser-tools
      - node/install-packages
      - run:
          name: Run Tests
          command: |
            cd ui_tests && npm run test
      - store_test_results:
          path: ./ui_tests/tests_output
      - run:
          name: Run API Tests
          command: |
            cd ../api_tests && npm run test

workflows:
  e2e-test:
    jobs:
      - test