version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  test:
    docker:
      - image: cimg/node:23.1
    steps:
      - checkout
      - run:
          name: Install Chrome
          command: |
            sudo apt-get update
            sudo apt-get install -y wget gnupg2
            wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
            sudo apt-get update
            sudo apt-get install -y google-chrome-stable
      - run:
          name: Run tests
          command: cd ui_tests && npm install && npm run test
      - store_test_results:
          path: ./ui_tests/tests_output
      - run:
          name: Start API Server
          command: cd ./api_tests && npm install && npm run dev &
      - run:
          name: Run API Tests
          command: cd ./api_tests && npm install && npm test
      - store_test_results:
          path: ./api_tests/reports/junit
            
workflows:
  e2e-test:
    jobs:
      - test