version: 2.1

orbs:
  node: circleci/node@4.7
  browser-tools: circleci/browser-tools@1.1.0

jobs:
  test:
    docker:
      - image: cimg/node:lts-browsers
    steps:
      - checkout
      - browser-tools/install-browser-tools
      - node/install-packages
      - run:
          name: Run UI Tests
          command: cd ui_tests && npm install && npm run test > output.log 2>&1
      - store_artifacts:
          path: ./ui_tests/output.log
      - store_test_results:
          path: ./ui_tests/tests_output
      - run:
          name: Start API Server
          command: cd ../api_tests && npm install &&  nohup npm run dev &
      - run:
          name: Run API Tests
          command: npm test
      - store_test_results:
          path: ./api_tests/reports/junit
            

workflows:
  e2e-test:
    jobs:
      - test